image: alpine:3.18

stages:
  - test
  - build


test:
  stage: test
  script: 
    - echo "No tests performed; returning true to enable merge requests"
    - echo true
  only:
    - merge_requests

call-webhook:
  stage: build
  script: 
    - apk add py3-pip
    - pip install requests
    - python call_webhook.py
  only:
    - main
